# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         XML-SAX
version:      0.96
version_from: SAX.pm
installdirs:  site
requires:
    File::Temp:                    0
    XML::NamespaceSupport:         0.03

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
