--- #YAML:1.0
name:                MailTools
version:             2.04
abstract:            Various Mail related modules
license:             perl
author:              
    - Mark Overmeer <perl@overmeer.net>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Date::Format:                  0
    Date::Parse:                   0
    IO::Handle:                    0
    Net::Domain:                   1.05
    Net::SMTP:                     1.03
    Test::More:                    0
    Test::Pod:                     1
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
