---
abstract: 'Tools to manipulate MIME messages'
author:
  - 'Eryq <eryq@zeegee.com>, David F. Skoll <dfs@roaringpenguin.com>, Dave O''Neill <dmo@roaringpenguin.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.95'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MIME-tools
no_index:
  directory:
    - examples
    - inc
    - t
recommends:
  MIME::Base64: 3.03
requires:
  File::Path: 1
  File::Spec: 0.6
  File::Temp: 0.18
  IO::File: 1.13
  IO::Handle: 0
  IO::Stringy: 2.11
  MIME::Base64: 2.2
  Mail::Field: 1.05
  Mail::Header: 1.01
  Mail::Internet: 1.0203
  perl: 5.8.0
resources:
  license: http://dev.perl.org/licenses/
version: 5.428
